const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],pad=n=>String(n).padStart(2,'0');
const KEY='daily-v8';
let old={};try{old=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('daily-v7')||localStorage.getItem('daily-v2')||localStorage.getItem('daily-v1')||'{}')}catch{}
let state={places:{home:{label:'Tatartie 3 C 8',lat:60.2324275,lon:24.7770787},school:{label:'Mattlidens IB Gymnasium',lat:60.1634437,lon:24.7500579}},destination:'school',events:{},renames:{},notifications:{enabled:false,beforeMin:10,classEnd:true},...old};state.places={home:{label:'Tatartie 3 C 8',lat:60.2324275,lon:24.7770787},school:{label:'Mattlidens IB Gymnasium',lat:60.1634437,lon:24.7500579},...(old.places||{})};state.events=old.events||{};state.renames=old.renames||{};state.notifications={enabled:false,beforeMin:10,classEnd:true,...(old.notifications||{})};
if(state.parserVersion!==8){state.parserVersion=8;if(state.icsSource?.url)state.icsSource.lastSync=0}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));save();let offset=0;
const dayAt=(o=0)=>{let d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+o);return d},iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,mins=t=>{let[h,m]=t.split(':').map(Number);return h*60+m};
const SUBJECTS=[
  ['MAG','Mathematics'],['MAA','Mathematics'],['MAB','Mathematics'],
  ['FY','Physics'],['KE','Chemistry'],['BI','Biology'],['GE','Geography'],
  ['HI','History'],['ENA','English'],['FIN','Finnish'],['RUA','Swedish'],['RUB','Swedish'],
  ['MO','Swedish'],['FI','Philosophy'],['PS','Psychology'],['YH','Social studies'],
  ['UE','Religion'],['ET','Ethics'],['TE','Health education'],['HÄ','Health education'],
  ['LI','Physical education'],['GY','Physical education'],['MU','Music'],['KU','Visual arts'],
  ['OP','Study guidance']
];
function codesFrom(v){return [...new Set((String(v||'').toUpperCase().match(/[A-ZÅÄÖ]{2,5}[O]?\d{1,3}(?:\.[A-Z0-9-]+)?/g)||[]).map(x=>x.replace(/[.,;:]$/,'')))]}
function bareCode(c){return String(c||'').toUpperCase().replace(/\.[A-Z0-9-]+$/,'')}
function family(c){let x=bareCode(c);for(let [p] of SUBJECTS)if(x.startsWith(p))return p;return ''}
function subjectNameFromCodes(cs){let names=[];for(let c of cs){let f=family(c),n=SUBJECTS.find(x=>x[0]===f)?.[1];if(n&&!names.includes(n))names.push(n)}return names.join(' + ')}
function importedCodes(e){return codesFrom([e.code,e.rawSummary,e.name].filter(Boolean).join(' '))}
function autoName(e){let n=subjectNameFromCodes(importedCodes(e));if(n)return n;let raw=String(e.name||e.rawSummary||'Lesson').replace(/\s*\([^)]*\)\s*/g,' ').replace(/\s+/g,' ').trim();return raw||'Lesson'}
function rkey(e){let cs=importedCodes(e),fs=[...new Set(cs.map(family).filter(Boolean))];if(fs.length===1)return 'SUBJECT:'+fs[0];if(cs.length)return 'COURSE:'+cs.map(bareCode).sort().join('+');return 'RAW:'+String(e.rawSummary||e.name||'Lesson').trim().toUpperCase()}
function legacyKey(e){return String(e.code||e.rawSummary||e.name||'').trim().toUpperCase()}
function display(e){return state.renames[rkey(e)]||state.renames[legacyKey(e)]||autoName(e)}
function norm(s){return String(s||'').toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[^a-z0-9åäö]+/g,' ').trim()}
function mergeSlot(group){let first=group[0],cs=[...new Set(group.flatMap(importedCodes))],rooms=[...new Set(group.map(x=>x.room).filter(Boolean))],raw=[...new Set(group.map(x=>x.rawSummary).filter(Boolean))];return{...first,code:cs.join(' · ')||first.code||'',room:rooms[0]||'',rawSummary:raw.join(' / ')||first.rawSummary||'',name:subjectNameFromCodes(cs)||autoName(first),mergedCount:group.length}}
function dedupe(xs){let bySlot=new Map();for(let e of [...xs].sort((a,b)=>a.start.localeCompare(b.start)||a.end.localeCompare(b.end))){let k=e.start+'|'+e.end;(bySlot.get(k)||bySlot.set(k,[]).get(k)).push(e)}return [...bySlot.values()].map(mergeSlot).sort((a,b)=>a.start.localeCompare(b.start)||a.end.localeCompare(b.end))}
function lessons(d){return dedupe(state.events?.[iso(d)]||[]).map(e=>({...e,name:display(e)}))}
const empty=(a,b)=>`<div class="empty"><h3>${esc(a)}</h3><p>${esc(b)}</p></div>`;
function nav(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.bottom-nav [data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));scrollTo({top:0,behavior:'smooth'});if(id==='schedule')renderSchedule()}
function bindRows(root,all){root.querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>editLesson(all[+el.dataset.i]))}
function renderToday(){let all=lessons(dayAt()),now=new Date(),n=now.getHours()*60+now.getMinutes(),cur=all.find(x=>mins(x.start)<=n&&n<mins(x.end)),next=all.find(x=>mins(x.start)>n),fin=all.length&&n>=mins(all.at(-1).end),f=cur||next;if(fin){let t=lessons(dayAt(1))[0];$('#focusLabel').textContent='TOMORROW';$('#focusName').textContent=t?.name||'Tomorrow is clear';$('#focusDetail').textContent=t?`Tomorrow · ${t.start}${t.room?' · '+t.room:''}`:'Enjoy the rest of the day.';$('#focusCountdown').textContent=t?'TOMORROW':'FREE';$('#focusHint').textContent='School is finished for today.'}else if(f){let diff=cur?mins(cur.end)-n:mins(f.start)-n;$('#focusLabel').textContent=cur?'IN CLASS':'UP NEXT';$('#focusName').textContent=f.name;$('#focusDetail').textContent=`${f.start}–${f.end}${f.room?' · '+f.room:''}`;$('#focusCountdown').textContent=cur?`ENDS ${f.end} · ${diff} MIN`:`IN ${diff} MIN`;$('#focusHint').textContent=cur?`Class ends at ${f.end}.`:'Take a breather before class.'}else{$('#focusLabel').textContent='FREE';$('#focusName').textContent='No lessons today';$('#focusDetail').textContent='A little room to breathe.';$('#focusCountdown').textContent='FREE';$('#focusHint').textContent='Import your Wilma calendar when ready.'}$('#schoolDaySummary').textContent=all.length?`${all.length} lessons · ends ${all.at(-1).end}`:'No lessons today';$('#todayTimeline').innerHTML=all.map((x,i)=>`<div class="lesson-row ${cur===x?'current':''}" data-i="${i}"><span class="lesson-time">${x.start}<br>${x.end}</span><span class="lesson-content"><strong>${esc(x.name)}</strong><small>${esc(x.code||x.rawSummary||'')}${x.room?' · '+esc(x.room):''}</small></span><span class="duration">${mins(x.end)-mins(x.start)}m</span></div>`).join('')||empty('Nothing scheduled','Import your Wilma ICS calendar to see classes here.');bindRows($('#todayTimeline'),all)}
function renderSchedule(){let d=dayAt(offset),all=lessons(d);$('#scheduleDay').textContent=offset===0?'Today':offset===1?'Tomorrow':d.toLocaleDateString('en-GB',{weekday:'long'});$('#scheduleDate').textContent=d.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'});$('#scheduleList').innerHTML=all.map((x,i)=>`<article class="schedule-event" data-i="${i}"><time>${x.start}<br>${x.end}</time><div><h3>${esc(x.name)}</h3><p>${esc(x.code||x.rawSummary||'')}${x.room?' · '+esc(x.room):''}</p></div><span class="duration">${mins(x.end)-mins(x.start)}m</span></article>`).join('')||empty('No classes','Import or sync your Wilma calendar.');bindRows($('#scheduleList'),all)}
function sheet(html){$('#sheetContent').innerHTML=html;$('#sheet').classList.add('open')}function close(){$('#sheet').classList.remove('open')}function toast(m){$('.toast')?.remove();let t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
function editLesson(e){let k=rkey(e),automatic=autoName(e);sheet(`<h2>Rename lesson</h2><p>Automatic name: <strong>${esc(automatic)}</strong><br><span class="tiny-note">${esc(e.code||e.rawSummary||'Imported from Wilma')}</span></p><input id="rn" class="input" placeholder="${esc(automatic)}" value="${esc(state.renames[k]||'')}"><button class="primary-btn" id="saveRn">Save custom name</button><button class="secondary-btn" id="resetRn">Use automatic name</button>`);$('#saveRn').onclick=()=>{let v=$('#rn').value.trim();v?state.renames[k]=v:delete state.renames[k];save();close();renderToday();renderSchedule()};$('#resetRn').onclick=()=>{delete state.renames[k];delete state.renames[legacyKey(e)];save();close();renderToday();renderSchedule()}}
function renameManager(){let all=Object.values(state.events).flat(),keys=[...new Set(all.map(rkey).filter(Boolean))].sort();sheet(`<h2>Rename lessons</h2><p>Daily cleans Wilma course codes automatically. Your custom names override the automatic names and stay after every sync.</p><div class="rename-list">${keys.map((k,i)=>{let e=all.find(x=>rkey(x)===k);return `<button class="rename-row" data-r="${i}"><span><strong>${esc(state.renames[k]||autoName(e))}</strong><small>${esc(e?.code||e?.rawSummary||k)}</small></span><b>›</b></button>`}).join('')||'<p>No imported lessons yet.</p>'}</div>`);$('[data-r]').forEach(b=>b.onclick=()=>editLesson(all.find(x=>rkey(x)===keys[+b.dataset.r])))}
function unfold(t){return t.replace(/\r\n/g,'\n').replace(/\r/g,'\n').replace(/\n[ \t]/g,'')}
function line(s){let i=s.indexOf(':');if(i<0)return null;let left=s.slice(0,i),value=s.slice(i+1),[name,...ps]=left.split(';'),params={};ps.forEach(p=>{let j=p.indexOf('=');if(j>0)params[p.slice(0,j).toUpperCase()]=p.slice(j+1)});return{name:name.toUpperCase(),params,value}}
function unesc(s=''){return s.replace(/\\n/gi,'\n').replace(/\\,/g,',').replace(/\\;/g,';').replace(/\\\\/g,'\\')}
function durationMs(v){let m=String(v||'').match(/^P(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?)?$/);return m?(((+m[1]||0)*24+(+m[2]||0))*60+(+m[3]||0))*60000+(+m[4]||0)*1000:0}
function helsinkiParts(d){let parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Helsinki',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d),o={};parts.forEach(x=>o[x.type]=x.value);return{date:o.year+'-'+o.month+'-'+o.day,time:o.hour+':'+o.minute}}
function parseIcsMoment(prop){if(!prop)return null;let v=String(prop.value||''),m=v.match(/^(\d{4})(\d{2})(\d{2})(?:T(\d{2})(\d{2})(\d{2})?)?(Z)?$/);if(!m)return null;let[,Y,M,D,h,mi,s='00',z]=m,allDay=!h||prop.params?.VALUE==='DATE';if(allDay)return{date:`${Y}-${M}-${D}`,time:null,allDay:true};if(z){let d=new Date(Date.UTC(+Y,+M-1,+D,+h,+mi,+s));return{...helsinkiParts(d),allDay:false,utcMs:d.getTime()}}return{date:`${Y}-${M}-${D}`,time:`${h}:${mi}`,allDay:false}}
function wallStamp(m){return Date.parse(m.date+'T'+(m.time||'00:00')+':00Z')}
function addMinutesWall(m,n){let d=new Date(wallStamp(m)+n*60000);return{date:d.toISOString().slice(0,10),time:d.toISOString().slice(11,16),allDay:false}}
function diffMinutes(a,b){return Math.max(1,Math.round((wallStamp(b)-wallStamp(a))/60000))}
function dateUTC(k){let [y,m,d]=k.split('-').map(Number);return new Date(Date.UTC(y,m-1,d))}
function dateKeyUTC(d){return d.toISOString().slice(0,10)}
function dayDistance(a,b){return Math.round((dateUTC(a)-dateUTC(b))/86400000)}
function feedWindow(url){let past=28,future=56;try{let u=new URL(url||location.href,location.href),ps=u.searchParams.get('p'),fs=u.searchParams.get('f');if(ps!==null){let p=Number(ps);if(Number.isFinite(p)&&p>=0)past=Math.min(p,180)}if(fs!==null){let f=Number(fs);if(Number.isFinite(f)&&f>=0)future=Math.min(f,366)}}catch{}let today=iso(dayAt());return{today,past,future}}
function parseRule(s){let o={};String(s||'').split(';').filter(Boolean).forEach(x=>{let i=x.indexOf('=');if(i>0)o[x.slice(0,i).toUpperCase()]=x.slice(i+1)});return o}
function makeOccurrence(base,start,end){return{uid:base.uid,rawSummary:base.rawSummary,name:base.name,code:base.code,room:base.room,start:start.time,end:end.time,date:start.date}}
function parseICS(text,sourceUrl=''){let blocks=unfold(text).split('BEGIN:VEVENT').slice(1),masters=[],overrides=[],single=[],win=feedWindow(sourceUrl),today=win.today;
  for(let raw of blocks){let p={};for(let l of raw.split('END:VEVENT')[0].split('\n')){let q=line(l.trim());if(q)(p[q.name]??=[]).push(q)}
    let sp=parseIcsMoment(p.DTSTART?.[0]);if(!sp||sp.allDay)continue;
    let status=String(p.STATUS?.[0]?.value||'').toUpperCase(),uid=unesc(p.UID?.[0]?.value||''),sum=unesc(p.SUMMARY?.[0]?.value||'Lesson'),room=unesc(p.LOCATION?.[0]?.value||''),cs=codesFrom(sum),code=cs.join(' · '),name=subjectNameFromCodes(cs)||sum.replace(/\s*\([^)]*\)\s*/g,' ').replace(/\s+/g,' ').trim()||'Lesson';
    let ep=parseIcsMoment(p.DTEND?.[0]),dm=durationMs(p.DURATION?.[0]?.value);if(!ep)ep=addMinutesWall(sp,dm?Math.max(1,Math.round(dm/60000)):60);
    let base={uid,rawSummary:sum,name,code,room,startMoment:sp,endMoment:ep,duration:diffMinutes(sp,ep),status,rrule:p.RRULE?.[0]?.value||'',recurrence:parseIcsMoment(p['RECURRENCE-ID']?.[0]),exdates:(p.EXDATE||[]).flatMap(x=>x.value.split(',')).map(v=>parseIcsMoment({value:v,params:x.params})).filter(Boolean),rdates:(p.RDATE||[]).flatMap(x=>x.value.split(',')).map(v=>parseIcsMoment({value:v,params:x.params})).filter(Boolean)};
    if(base.recurrence)overrides.push(base);else if(base.rrule)masters.push(base);else single.push(base)
  }
  let occ=new Map(),key=(uid,m)=>((uid||'NOUID')+'|'+m.date+'|'+m.time),inside=m=>{let d=dayDistance(m.date,today);return d>=-win.past-2&&d<=win.future+2};
  for(let b of single){if(b.status==='CANCELLED'||!inside(b.startMoment))continue;occ.set(key(b.uid,b.startMoment),makeOccurrence(b,b.startMoment,b.endMoment))}
  for(let b of masters){if(b.status==='CANCELLED')continue;let r=parseRule(b.rrule),freq=r.FREQ||'',interval=Math.max(1,Number(r.INTERVAL)||1),count=r.COUNT?Math.max(1,Number(r.COUNT)||1):Infinity,until=r.UNTIL?parseIcsMoment({value:r.UNTIL,params:{}}):null,by=(r.BYDAY||'').split(',').filter(Boolean).map(x=>x.slice(-2)),weekday={SU:0,MO:1,TU:2,WE:3,TH:4,FR:5,SA:6},startD=dateUTC(b.startMoment.date),limitD=dateUTC(addMinutesWall({date:today,time:'00:00'},(win.future+3)*1440).date),seen=0,guard=0;
    const addAt=d=>{if(seen>=count)return false;let sm={date:dateKeyUTC(d),time:b.startMoment.time,allDay:false};if(until&&(sm.date>until.date||(sm.date===until.date&&until.time&&sm.time>until.time)))return false;seen++;let excluded=b.exdates.some(x=>x.date===sm.date&&(!x.time||x.time===sm.time));if(!excluded&&inside(sm)){let em=addMinutesWall(sm,b.duration);occ.set(key(b.uid,sm),makeOccurrence(b,sm,em))}return true};
    if(freq==='DAILY'){for(let d=new Date(startD);d<=limitD&&guard++<800&&seen<count;d.setUTCDate(d.getUTCDate()+interval)){if(!addAt(d))break}}
    else if(freq==='WEEKLY'){let allowed=by.length?by.map(x=>weekday[x]).filter(x=>x!==undefined):[startD.getUTCDay()];for(let d=new Date(startD);d<=limitD&&guard++<1000&&seen<count;d.setUTCDate(d.getUTCDate()+1)){let days=Math.floor((d-startD)/86400000),week=Math.floor(days/7);if(week%interval===0&&allowed.includes(d.getUTCDay())){if(!addAt(d))break}}}
    else if(freq==='MONTHLY'){for(let d=new Date(startD),n=0;d<=limitD&&guard++<120&&seen<count;n+=interval){d=new Date(Date.UTC(startD.getUTCFullYear(),startD.getUTCMonth()+n,startD.getUTCDate()));if(!addAt(d))break}}
    else if(inside(b.startMoment))occ.set(key(b.uid,b.startMoment),makeOccurrence(b,b.startMoment,b.endMoment));
    for(let rd of b.rdates){if(rd.allDay||!inside(rd))continue;let em=addMinutesWall(rd,b.duration);occ.set(key(b.uid,rd),makeOccurrence(b,rd,em))}
  }
  for(let b of overrides){let rid=b.recurrence,oldKey=key(b.uid,rid);occ.delete(oldKey);if(b.status==='CANCELLED'||!inside(b.startMoment))continue;occ.set(key(b.uid,b.startMoment),makeOccurrence(b,b.startMoment,b.endMoment))}
  let out={};for(let e of occ.values()){if(!e.start||!e.end)continue;(out[e.date]??=[]).push(e)}Object.keys(out).forEach(k=>out[k]=dedupe(out[k]));return out
}
function applyICS(text,source,quiet=false){if(!/BEGIN:VCALENDAR/i.test(text))throw 0;let events=parseICS(text,source?.url||state.icsSource?.url||'');if(!Object.keys(events).length)throw 0;state.events=events;if(source?.url)state.icsSource=source;else if(source?.file)delete state.icsSource;save();refreshCalendar();renderToday();renderSchedule();if(!quiet)toast(`Imported ${Object.values(events).flat().length} lesson entries.`)}
function refreshCalendar(){if(state.icsSource?.url){let t=state.icsSource.lastSync?new Date(state.icsSource.lastSync).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—';$('#calendarSource').textContent=`CALENDAR LINK · SYNCED ${t}`;$('#icsStatus').textContent=`Calendar link · synced ${t}`}else if(Object.keys(state.events).length){$('#calendarSource').textContent='IMPORTED ICS FILE';$('#icsStatus').textContent='ICS file imported'}else{$('#calendarSource').textContent='NO CALENDAR CONNECTED';$('#icsStatus').textContent='No timetable imported'}}
function importSheet(){sheet(`<h2>Import timetable</h2><p>Import a Wilma .ics file or paste an ICS subscription link.</p><button class="primary-btn" id="pick">Choose ICS file</button><input id="url" class="input" placeholder="https://…/calendar.ics"><button class="secondary-btn" id="link">Import calendar link</button><p class="tiny-note">iOS can suspend a Home Screen web app when fully closed, so background sync and local notifications are not guaranteed while the app is killed.</p>`);$('#pick').onclick=()=>$('#icsFile').click();$('#link').onclick=async()=>{let url=$('#url').value.trim();if(!url)return;try{let r=await fetch('/api/ics',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})});if(!r.ok)throw 0;applyICS(await r.text(),{url,lastSync:Date.now()});close()}catch{toast('Calendar link could not be imported.')}}}
async function sync(silent=true){if(!state.icsSource?.url)return;if(silent&&state.icsSource.lastSync&&Date.now()-state.icsSource.lastSync<9e5)return;try{let r=await fetch('/api/ics',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:state.icsSource.url})});if(!r.ok)throw 0;applyICS(await r.text(),{url:state.icsSource.url,lastSync:Date.now()},silent)}catch{if(!silent)toast('Sync failed. Existing timetable kept.')}}
async function geo(q){let j=await fetch('/api/geocode?q='+encodeURIComponent(q)).then(r=>r.json());return(j.features||[]).map(x=>({label:x.label,lat:x.geometry.coordinates[1],lon:x.geometry.coordinates[0],type:x.type}))}function choice(input,box){input.oninput=()=>{clearTimeout(input._t);input._t=setTimeout(async()=>{if(input.value.trim().length<2){box.innerHTML='';return}try{let xs=await geo(input.value.trim());box.innerHTML=xs.map((x,i)=>`<button class="suggestion" data-g="${i}">${esc(x.label)}</button>`).join('');box.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>{let x=xs[+b.dataset.g];input.value=x.label;input._place=x;box.innerHTML=''})}catch{}},250)}}function transportPlaces(){return state.destination==='school'?{from:state.places.home,to:state.places.school}:{from:state.places.school,to:state.places.home}}function renderTransport(){let{from,to}=transportPlaces();$('#homeAddress').textContent=state.places.home.label;$('#schoolAddress').textContent=state.places.school.label;$('#fromInput').value=from.label;$('#toInput').value=to.label;$('#fromInput')._place=from;$('#toInput')._place=to;$('#transportContext').textContent=state.destination==='school'?'TO SCHOOL':'TO HOME';$('#stopName').textContent=`${from.label} → ${to.label}`;$$('[data-destination]').forEach(b=>b.classList.toggle('active',b.dataset.destination===state.destination))}function hsl(a,b){let p=x=>`${encodeURIComponent(x.label)}%3A%3A${x.lat}%2C${x.lon}`;return`https://reittiopas.hsl.fi/reitti/${p(a)}/${p(b)}`}function plan(){let a=$('#fromInput')._place,b=$('#toInput')._place;if(!a||!b)return toast('Choose both places first.');location.href=hsl(a,b)}function setPlace(k){sheet(`<h2>${k==='home'?'Home':'School'} location</h2><input id="pl" class="input" value="${esc(state.places[k].label)}"><div id="prs"></div>`);let i=$('#pl'),r=$('#prs');i.oninput=()=>{clearTimeout(i._t);i._t=setTimeout(async()=>{let xs=await geo(i.value);r.innerHTML=xs.map((x,n)=>`<button class="search-result" data-p="${n}">${esc(x.label)}</button>`).join('');r.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{state.places[k]=xs[+b.dataset.p];save();close();renderTransport()})},250)}}
async function notify(title,body,key){if(Notification.permission!=='granted')return;let d=JSON.parse(localStorage.getItem('daily-notified')||'{}');if(d[key])return;d[key]=Date.now();localStorage.setItem('daily-notified',JSON.stringify(d));try{let reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,tag:key,icon:'/icons/icon-192.png'})}catch{}}function tick(){if(!state.notifications.enabled||!('Notification'in window)||Notification.permission!=='granted')return;let now=new Date(),days=[iso(now),iso(dayAt(1))];for(let day of days)for(let e of dedupe(state.events?.[day]||[]))for(let [kind,time,body] of [['before',e.start,`${display(e)} starts at ${e.start}.`],['end',e.end,`${display(e)} ends now.`]]){if(kind==='end'&&!state.notifications.classEnd)continue;let[h,m]=time.split(':').map(Number),t=new Date(day+'T00:00:00');t.setHours(h,m-(kind==='before'?state.notifications.beforeMin:0),0,0);if(Math.abs(now-t)<9e4)notify(kind==='before'?'Lesson soon':'Class ended',body,`${day}-${time}-${kind}-${rkey(e)}`)}}
async function weather(){try{let j=await fetch('https://api.open-meteo.com/v1/forecast?latitude=60.2055&longitude=24.6559&current=temperature_2m').then(r=>r.json());$('#weather').textContent=`ESPOO · ${Math.round(j.current.temperature_2m)}°`}catch{$('#weather').textContent='ESPOO · OFFLINE'}}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#viewSchedule').onclick=()=>nav('schedule');$('#closeSheet').onclick=close;$('#sheet').onclick=e=>e.target===$('#sheet')&&close();$('#themeBtn').onclick=$('#themeRow').onclick=()=>{document.body.classList.toggle('dark');state.dark=document.body.classList.contains('dark');save()};if(state.dark)document.body.classList.add('dark');$('#prevDay').onclick=()=>{offset--;renderSchedule()};$('#nextDay').onclick=()=>{offset++;renderSchedule()};$('#settingsIcs').onclick=$('#importIcs').onclick=$('#syncCalendar').onclick=importSheet;$('#icsFile').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;try{applyICS(await f.text(),{file:true});close()}catch{toast('We could not read that ICS file.')}e.target.value=''};$('#renameLessons').onclick=renameManager;$('#clearIcs').onclick=()=>{state.events={};delete state.icsSource;save();refreshCalendar();renderToday();renderSchedule();toast('Timetable removed.')};$('#notifyBtn').onclick=async()=>{if(!('Notification'in window))return toast('Notifications are unavailable here.');let p=await Notification.requestPermission();state.notifications.enabled=p==='granted';save();$('#notifyStatus').textContent=p==='granted'?'On · 10 min before + class end':'Off · permission not granted'};$('#homePlace').onclick=()=>setPlace('home');$('#schoolPlace').onclick=()=>setPlace('school');$('#planRoute').onclick=plan;$$('[data-destination]').forEach(b=>b.onclick=()=>{state.destination=b.dataset.destination;save();renderTransport()});$('#useLocation').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{$('#fromInput')._place={label:'Current location',lat:p.coords.latitude,lon:p.coords.longitude};$('#fromInput').value='Current location';$('#locationStatus').textContent='Using your live location.'},()=>$('#locationStatus').textContent='Location permission was not granted.');choice($('#fromInput'),$('#fromSuggestions'));choice($('#toInput'),$('#toSuggestions'));$('#todayDate').textContent=new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short'}).toUpperCase();refreshCalendar();renderToday();renderSchedule();renderTransport();weather();tick();sync(true);setInterval(()=>{renderToday();tick()},30000);setInterval(()=>sync(true),9e5);addEventListener('focus',()=>sync(true));document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync(true)});